// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are only configured for web.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcFwkYsp64HNZVgsY86TC7aE2_VM1SIqQ',
    appId: '1:282482672251:web:2c68d577580e00a08058de',
    messagingSenderId: '282482672251',
    projectId: 'le-cocon-ssbe-6a4d0',
    authDomain: 'le-cocon-ssbe-6a4d0.firebaseapp.com',
    storageBucket: 'le-cocon-ssbe-6a4d0.appspot.com',
  );
}
