// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcFwkYsp64HNZVgsY86TC7aE2_VM1SIqQ',
    appId: '1:282482672251:web:2c68d577580e00a08058de',
    messagingSenderId: '282482672251',
    projectId: 'le-cocon-ssbe-6a4d0',
    authDomain: 'le-cocon-ssbe-6a4d0.firebaseapp.com',
    storageBucket: 'le-cocon-ssbe-6a4d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPY_nMXp21PcJdh9GpNhHWHMwtamOny78',
    appId: '1:282482672251:web:2c68d577580e00a08058de',
    messagingSenderId: '282482672251',
    projectId: 'le-cocon-ssbe-6a4d0',
    storageBucket: 'le-cocon-ssbe-6a4d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHXNBKxfWEqoD-1HcwYIKM8MQzRNwYnNA',
    appId: '1:282482672251:web:2c68d577580e00a08058de',
    messagingSenderId: '282482672251',
    projectId: 'le-cocon-ssbe-6a4d0',
    storageBucket: 'le-cocon-ssbe-6a4d0.appspot.com',
    iosBundleId: 'com.example.appLecoconSsbe',
  );


}
